Repository didx-xyz/ssi-trust-registry, pull requests merged in 2023-10, with the labels that each got.

#120 Install `node-gyp` in CICD
  .github/workflows/ci-cd.yml
Labels: bug

#119 [Snyk] Security upgrade zod from 3.22.2 to 3.22.3
  package.json
  yarn.lock
Labels: dependencies, javascript

#129 Add Yarn empty dir volumes
  .github/workflows/ci-cd.yml
  helm/trust-registry/Chart.lock
  helm/trust-registry/Chart.yaml
  helm/trust-registry/values.yaml
Labels: bug

#135 Node 20
  .github/workflows/ci-cd.yml
  .tool-versions
  Dockerfile
  Tiltfile
  helm/trust-registry/Chart.lock
  helm/trust-registry/Chart.yaml
Labels: dependencies, chore
